env:
  browser: true
  es2021: true
extends:
  # https://github.com/standard/eslint-config-standard
  - standard

  # https://github.com/yannickcr/eslint-plugin-react
  - plugin:react/recommended

  # https://github.com/benmosher/eslint-plugin-import
  - plugin:import/recommended
  - plugin:import/react
  - plugin:import/typescript

  # https://github.com/typescript-eslint/typescript-eslint
  - plugin:@typescript-eslint/recommended

  # https://github.com/prettier/eslint-config-prettier
  - prettier

  # https://github.com/prettier/eslint-plugin-prettier
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
  - prettier
rules:
  prettier/prettier: warn
  no-use-before-define: 0 # https://github.com/typescript-eslint/typescript-eslint/issues/2502
  import/order: # https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
    - "warn"
    - alphabetize: { order: asc, caseInsensitive: true }
      groups:
        [
          "builtin",
          "external",
          "internal",
          "type",
          "parent",
          "sibling",
          "index",
        ]
      newlines-between: always
      pathGroups:
        - { pattern: "~/**", group: "parent" }
  import/no-unresolved: 0
  import/no-default-export: warn
  "@typescript-eslint/explicit-module-boundary-types":
    [1, { allowedNames: [render] }]
  "react-hooks/rules-of-hooks": "error" # https://reactjs.org/docs/hooks-rules.html
  "react-hooks/exhaustive-deps": "warn"
  no-console: [1, { allow: ["warn", "error", "trace"] }]
overrides:
  - files: ["src/App.tsx"]
    rules:
      import/no-default-export: 0
  - files: ["src/reportWebVitals.ts"]
    rules:
      "@typescript-eslint/explicit-module-boundary-types": 0
      import/no-default-export: 0
  - files: ["src/pages/**/*"]
    rules:
      import/no-default-export: 0
settings:
  react:
    version: detect
ignorePatterns:
  - "out"
